[functions.embedding-worker]
enabled = true
verify_jwt = true
import_map = "./functions/embedding-worker/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/embedding-worker/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/embedding-worker/*.html" ]

[functions.summarization-agent]
enabled = true
verify_jwt = true
import_map = "./functions/summarization-agent/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/summarization-agent/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/summarization-agent/*.html" ]
